"""Flight Tracker Application using Amadeus API"""

from io import StringIO
import os
import json
import base64
import sqlite3
from pprint import pprint
from email.message import EmailMessage
from pathlib import Path
from datetime import datetime
import google.auth
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from amadeus import Client, ResponseError
from dotenv import load_dotenv
from flask import Flask, current_app, redirect, render_template, request, g


load_dotenv()

app = Flask(__name__)

BASE_DIR = Path(__file__).resolve().parent
DEFAULT_DB_PATH = BASE_DIR / "data" / "tracked.db"
DB_PATH = Path(os.getenv("DB_PATH", str(DEFAULT_DB_PATH)))

# Database connection preventing multiple thread usage issues.  Per copilot suggestion.


def get_db():
    if 'db' not in g:
        # Ensures data exists
        DB_PATH.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(DB_PATH))
        conn.row_factory = sqlite3.Row
        g.db = conn
    return g.db


@app.teardown_appcontext
def close_db(error=None):
    db = g.pop('db', None)
    if db is not None:
        db.close()


amadeus = Client(
    client_id=os.getenv("AMADEUS_API_KEY"),
    client_secret=os.getenv("AMADEUS_API_SECRET"),
    hostname='production'
)


AIRLINE_CODE_CACHE = {}

# Generated by Codex


def iso_duration_to_text(s):
    s = s.replace("PT", "")
    hours = minutes = 0
    if "H" in s:
        hours, s = s.split("H", 1)
        hours = int(hours or 0)
    if "M" in s:
        minutes = int(s.split("M", 1)[0] or 0)
    parts = []
    if hours:
        parts.append(f"{hours} hr")
    if minutes:
        parts.append(f"{minutes} min")
    return " ".join(parts) if parts else "0 min"


def get_airline_name(airline_code):
    """Function to look up airline name from 2-letter code"""
    if not airline_code or len(airline_code) != 2:
        return airline_code

    try:
        cached = AIRLINE_CODE_CACHE.get(airline_code)
        if cached:
            return cached

        airline_response = amadeus.reference_data.airlines.get(
            airlineCodes=airline_code)
        airline_name = airline_response.data[0]['commonName']
        AIRLINE_CODE_CACHE[airline_code] = airline_name
        return airline_name

    except ResponseError as error:
        print(f"An error occurred in airline lookup: {error}")
        return airline_code


def get_flight_offers(origin, destination, departure_date, adults, airline_code, max_results, nonstop):
    """Function to get flight offers from Amadeus API"""

    if departure_date < datetime.now().date().isoformat():
        print("Departure date is in the past.")
        return None

    try:
        params = dict(
            originLocationCode=origin,
            destinationLocationCode=destination,
            departureDate=departure_date,
            adults=adults,
            currencyCode='USD'
        )
        if airline_code:
            params['includedAirlineCodes'] = airline_code
        if max_results:
            params['max'] = int(max_results)
        if nonstop:
            params['nonStop'] = 'true'

        response = amadeus.shopping.flight_offers_search.get(**params)

        return response

    except ResponseError as error:
        print(
            f"An error occurred getting flight data, get_flight_offers failed: {error}")
        return None


def process_flight_data(response):
    """Function to process flight data from Amadeus response.  Pick needed data from JSON and create new list of dicts"""

    # Create an empty list to hold flight data for rendering in Flask
    flight_data = []

    for flight in response.data:
        legs = len(flight['itineraries'][0]['segments'])
        # Contains duration and segments
        itinerary = flight['itineraries'][0]
        # Contains each flight leg details
        segments = itinerary['segments']

        flight_info = {
            "search_no": flight['id'],
            "stops": (legs - 1),
            "departure_airport": segments[0]['departure']['iataCode'],
            "departure_time": segments[0]['departure']['at'],
            "arrival_airport": segments[-1]['arrival']['iataCode'],
            "arrival_time": segments[-1]['arrival']['at'],
            "duration": flight['itineraries'][0]['duration'],
            "carrier_code": flight['validatingAirlineCodes'][0],
            "price": flight['price']['grandTotal'],
            "bookable_seats": flight['numberOfBookableSeats'],
            "legs": []
        }

        for i in range(legs):
            flight_info_leg = {
                "leg_no": i + 1,
                "departure_airport": segments[i]['departure']['iataCode'],
                "departure_time": segments[i]['departure']['at'],
                "arrival_airport": segments[i]['arrival']['iataCode'],
                "arrival_time": segments[i]['arrival']['at'],
                "duration": segments[i]['duration'],
                "carrier_code": segments[i]['operating'].get('carrierCode') or
                segments[i]['operating'].get('carrierName'),
                "flight_number": segments[i]['number']
            }
            flight_info["legs"].append(flight_info_leg)

        flight_data.append(flight_info)

    # Iterate through flight dicts and update time and duration format, look up carrier.
    for flight in flight_data:
        dt = datetime.fromisoformat(flight.get("departure_time"))
        flight["departure_time"] = dt.strftime("%a, %b %d, %Y - %-I:%M %p")

        dt = datetime.fromisoformat(flight.get("arrival_time"))
        flight["arrival_time"] = dt.strftime("%a, %b %d, %Y - %-I:%M %p")

        flight["duration"] = iso_duration_to_text(flight.get('duration'))

        code = flight.get("carrier_code")

        if code:
            flight["carrier_code"] = get_airline_name(code)

        for leg in flight.get("legs", []):
            dt = datetime.fromisoformat(leg.get("departure_time"))
            leg["departure_time"] = dt.strftime("%a, %b %d, %Y - %-I:%M %p")

            dt = datetime.fromisoformat(leg.get("arrival_time"))
            leg["arrival_time"] = dt.strftime("%a, %b %d, %Y - %-I:%M %p")

            leg["duration"] = iso_duration_to_text(leg.get('duration'))

            code = leg.get("carrier_code")

            if code:
                leg["carrier_code"] = get_airline_name(code)

    # pprint(flight_data)

    return flight_data


# Straight up copied this from Codex.  Decided to do it the right way with OAuth2 and got in way deep.
def get_gmail_creds():

    SCOPES = ["https://www.googleapis.com/auth/gmail.send"]

    # SECRETS_DIR can be set in .env; otherwise default to "<app>/secrets"
    secrets_dir = os.getenv("SECRETS_DIR") or os.path.join(
        current_app.root_path, "secrets")

    secrets_dir = Path(secrets_dir)
    token_path = secrets_dir / "token.json"
    client_path = secrets_dir / "credentials.json"

    secrets_dir.mkdir(parents=True, exist_ok=True)

    creds = None
    if token_path.exists():
        creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
            except Exception:
                creds = None
        if not creds or not creds.valid:
            flow = InstalledAppFlow.from_client_secrets_file(
                str(client_path), SCOPES)
            creds = flow.run_local_server(port=0)
        token_path.write_text(creds.to_json())

    return creds


# Create function to email out results.  From Google Gmail API quickstart.
def gmail_send_message(flight_data, to_email, subject=None):
    """Email flight offers using Gmail API"""

    creds = get_gmail_creds()

    try:
        service = build("gmail", "v1", credentials=creds)
        message = EmailMessage()

        message['To'] = to_email
        message['From'] = "mspaitsdev@gmail.com"
        message['Subject'] = subject or "Flight Offers"

        message.set_content("Flight offers (text fallback).")
        html_body = render_template("email_template.html", flights=flight_data)
        message.add_alternative(html_body, subtype="html")

        # Encode the message
        encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()

        create_message = {'raw': encoded_message}
        # pyling: disable=E1101
        send_message = (service.users().messages().send(
            userId="me", body=create_message).execute())
        print(F'Message Id: {send_message["id"]}')

    except HttpError as error:
        print(f'An error occurred with mail: {error}')
        send_message = None
    return send_message


# Flask route to render a simple homepage
@app.route("/", methods=['GET', 'POST'])
def index():
    """Route for homepage and flight search"""

    print("Index route hit")

    if request.method == 'POST':
        # Get data from HTML form
        origin = request.form.get('origin').upper()
        if not origin or len(origin) != 3:
            return redirect("/")
        destination = request.form.get('destination').upper()
        if not destination or len(destination) != 3:
            return redirect("/")
        departure_date = request.form.get('departure_date')
        if not departure_date:
            return redirect("/")
        adults = int(request.form.get('adults', 1))
        if not adults:
            return redirect("/")
        airline_code = request.form.get('airline_code')
        if airline_code and len(airline_code) != 2:
            return redirect("/")
        max_results = request.form.get('max_results')
        nonstop = request.form.get('nonstop')

        # Call function to get flight offers
        response = get_flight_offers(
            origin=origin,
            destination=destination,
            departure_date=departure_date,
            adults=adults,
            airline_code=airline_code,
            max_results=max_results,
            nonstop=nonstop,
        )

        if response is None:
            return "get_flight_offers failed."

        flight_data = process_flight_data(response)

        return render_template('index.html', flights=flight_data)

    else:
        return render_template('index.html')


@app.route("/autotrack", methods=['GET', 'POST'])
def autotrack():
    """Route for auto-tracking flights.  Adds searches to the db and displays tracked searches."""

    if request.method == 'POST':
        # Get data from HTML form
        origin = request.form.get('origin').upper()
        if not origin or len(origin) != 3:
            return redirect("/autotrack")
        destination = request.form.get('destination').upper()
        if not destination or len(destination) != 3:
            return redirect("/autotrack")
        departure_date = request.form.get('departure_date')
        if not departure_date:
            return redirect("/autotrack")
        adults = int(request.form.get('adults', 1))
        if not adults:
            return redirect("/autotrack")
        airline_code = request.form.get('airline_code')
        if airline_code and len(airline_code) != 2:
            return redirect("/autotrack")
        max_results = request.form.get('max_results')
        email = request.form.get('email')
        nonstop = request.form.get('nonstop')

        # Apparently this is what you need to do to access Sqlite3 outside of CS50 IDE.
        db = get_db()
        cur = db.cursor()
        cur.execute("INSERT INTO searches (origin, destination, date, adults, results, airline, email, nonstop) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (origin, destination, departure_date, adults, max_results, airline_code, email, nonstop))
        db.commit()

        return redirect('/autotrack')

    else:

        # Retrieve tracked searches from the database to render on webpage
        db = get_db()
        cur = db.cursor()
        cur.execute("SELECT * FROM searches")

        tracked_table = []
        for row in cur.fetchall():  # Fetches all rows as crappy sqlite3.Row ojects at a memory address
            # Looks like this is how you can turn each row into a dict.
            row_dict = dict(row)
            dt = datetime.fromisoformat(row_dict.get("date"))
            row_dict["date"] = dt.strftime("%a, %b %d, %Y")
            nonstop_value = row_dict.get("nonstop")
            row_dict["nonstop"] = "Yes" if str(nonstop_value).lower() in (
                "true", "1", "yes", "on") else "No"
            tracked_table.append(row_dict)

        return render_template('autotrack.html', tracked_table=tracked_table)


@app.route("/check/<int:search_id>", methods=['POST'])
def check_search(search_id):
    """Route to check a tracked search immediately"""

    db = get_db()
    cur = db.cursor()
    cur.execute("SELECT * FROM searches WHERE id = ?", (search_id,))
    search = cur.fetchone()  # Fetches one row

    if search is None:
        return "Search not found.", 404

    if search['date'] < datetime.now().date().isoformat():
        return "Departure date is in the past."

    response = get_flight_offers(
        origin=search['origin'],
        destination=search['destination'],
        departure_date=search['date'],
        adults=search['adults'],
        airline_code=search['airline'],
        max_results=search['results'],
        nonstop=search['nonstop']
    )

    if response is None:
        return "get_flight_offers failed."

    # Save response to a JSON file
    # with open("flight_offers.json", "w", encoding="utf-8") as file:
       # json.dump(response.data, file, indent=2)
    # print("\nFlight offers saved to flight_offers.json")

    flight_data = process_flight_data(response)

    # send_daily_search()

    return render_template('index.html', flights=flight_data)


# I got this method of passing in the search_id from a copilot suggestion
@app.route("/delete/<int:search_id>", methods=['POST'])
def delete_search(search_id):
    """Route to delete a tracked search"""

    db = get_db()
    cur = db.cursor()
    cur.execute("DELETE FROM searches WHERE id = ?", (search_id,))
    db.commit()

    return redirect('/autotrack')


@app.route("/add_email/<int:search_id>", methods=['POST'])
def add_email(search_id):
    """Route to add an email and start auto track"""

    email = request.form.get('email')

    if email:
        db = get_db()
        cur = db.cursor()
        cur.execute("UPDATE searches SET email = ? WHERE id = ?",
                    (email, search_id,))
        db.commit()

    return redirect('/autotrack')


@app.route("/remove_email/<int:search_id>", methods=['POST'])
def remove_email(search_id):
    """Route to delete a email and stop auto track"""

    db = get_db()
    cur = db.cursor()
    cur.execute("UPDATE searches SET email = NULL WHERE id = ?", (search_id,))
    db.commit()

    return redirect('/autotrack')


# Setting up a scheduled task to send out search results daily
def send_daily_search():
    """Iterates through the saved search list.  If email present: searches flights, and emails results"""

    with app.app_context():
        db = get_db()
        cur = db.cursor()
        cur.execute(
            "SELECT * FROM searches WHERE email IS NOT NULL AND email != ''")
        searches = cur.fetchall()

        for search in searches:
            response = get_flight_offers(
                origin=search['origin'],
                destination=search['destination'],
                departure_date=search['date'],
                adults=search['adults'],
                airline_code=search['airline'],
                max_results=search['results'],
                nonstop=search['nonstop']
            )

            if response is None:
                continue

            # Reformat date
            search_dict = dict(search)
            dt = datetime.fromisoformat(search_dict.get("date"))
            search_dict["date"] = dt.strftime("%a, %b %d, %Y")

            flight_data = process_flight_data(response)
            subject = f"Flight Offers {search['origin']}->{search['destination']} {search_dict['date']}"
            gmail_send_message(flight_data, search['email'], subject=subject)
